In [6]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib as plt

df = sns.load_dataset("titanic")
print(df.shape)   # (891, 15)
df.head()

(891, 15)


,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


# Ovo nam je NUMPY vebanje koje je claude smislio
**Ispod je N1**

In [14]:
brojevi = np.arange(24)
print (brojevi)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [15]:
brojevi.reshape(4, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [17]:
brojevi.reshape(5,5)

ValueError: cannot reshape array of size 24 into shape (5,5)

In [18]:
brojevi += 1

In [19]:
print (brojevi)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [22]:
brojevi.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [23]:
nule = np.zeros(5, dtype=int)
print(nule)

[0 0 0 0 0]


**Ispod je N2**

In [25]:
m = np.arange(1, 26).reshape(5, 5)
print(m[2])

[11 12 13 14 15]


In [29]:
print(m[1:4, 1:4].sum())

117


In [32]:
print(m[::4,::4])

[[ 1  5]
 [21 25]]


In [37]:
print(m[np.arange(5), np.arange(5)].sum())

65


In [38]:
print(m[m%3 == 0])

[ 3  6  9 12 15 18 21 24]


In [39]:
print(m[::,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


**Ispod je N3**

In [41]:
ocene = np.array([
    [5, 4, 3, 5],
    [2, 3, 1, 3],
    [5, 5, 4, 4],
    [3, 2, 2, 1],
    [4, 5, 5, 5],
    [1, 3, 2, 4],
])
#axis 0 je po kolonama i to je predmet a axis 1 je po redovima i to je po uceniku
predmeti = np.array(["matematika", "fizika", "hemija", "biologija"])

In [49]:
minindeks = np.argmin(ocene.mean(axis = 0))
print(predmeti[minindeks])

hemija


In [58]:
a = np.any(ocene == 1, axis = 1)
np.count_nonzero(a)

np.int64(3)

In [59]:
np.sum(ocene == 5)

np.int64(7)

In [68]:
niz = ocene.mean(axis = 1)
print(ocene[niz>=4])

[[5 4 3 5]
 [5 5 4 4]
 [4 5 5 5]]


In [72]:
X = np.array([
    [50, 2, 10],
    [80, 3, 5],
    [120, 4, 20],
    [65, 2, 30],
])  # kvadratura, broj soba, starost stana
w = np.array([1500, 5000, -300])
b = 10000

rez = X@w+b
print(rez)

[ 92000 143500 204000 108500]


In [82]:
tacke = np.array([[0, 0], [3, 4], [6, 8], [1, 1]])
A = tacke[:, None, :]
B = tacke[None, :, :]

razlike = A-B
d = np.sqrt((razlike ** 2).sum(axis = 2))
print(d)


[[ 0.          5.         10.          1.41421356]
 [ 5.          0.          5.          3.60555128]
 [10.          5.          0.          8.60232527]
 [ 1.41421356  3.60555128  8.60232527  0.        ]]
